# platform :ios, '9.0'

target 'MaterialShowcaseExample' do
    use_frameworks!
    
    #pod 'MaterialShowcase'
    pod 'MaterialShowcase', '~> 0.5.1'
    #pod 'MaterialShowcase',:git => 'https://github.com/aromajoin/material-showcase-ios.git', :tag => '0.5.1'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name.include?('MaterialShowcase')
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
    
end
